
FROM mysql:latest

MAINTAINER bitespeed-mysql

RUN chown -R mysql:root /var/lib/mysql/

ARG MYSQL_DATABASE
ARG MYSQL_ROOT_HOST
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_HOST=%
ENV MYSQL_DATABASE=biteDB
ENV MYSQL_PASSWORD=Animal@13
ENV MYSQL_ROOT_PASSWORD=Animal@123


EXPOSE 3310

